apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: Loki
    isDefault: true
    version: 1
    editable: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: luminalib
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
    uid: LuminaLib-Postgres
    isDefault: false
    version: 1
    editable: true
